version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: programacao
      POSTGRES_DB: cursonodejs
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
